[package]

name = "zip"
version = "0.1.0"
authors = [
    "Jorge Gorbe <slack@codemaniacs.com>",
    "Kang Seonghoon <public+rust@mearie.org>",
    "Nikita Pekin <contact@nikitapek.in>"
]

[lib]

name = "zip"
path = "src/zip/lib.rs"

[[bin]]

name = "zip-demo"
path = "src/zip-demo/main.rs"
